### ISSUE TITLE
Should have way to disconnect timers

### ISSUE THREAD

**Issue by doctor3w** [Knowinnovation/bluetime#1]
Right now, once connected, the only way to disconnect is to go out of range or kill the app. I'm think we should have some button or something that allows that user to disconnect.

**Comment by andyburnett** [comment]
Sounds good, although just killing the app is probably fine for now

**Comment by andyburnett** [comment]
Actually, if I walk out of range and then come back into range, will it automagically reconnect?

**Comment by doctor3w** [comment]
I'm not sure I had that same question

**Comment by doctor3w** [comment]
No it won't.
