### ISSUE TITLE
Last connection needs to be restored when device 'wakes up'

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#18]
I have been using the timer today. It's great, and we need a better way of re-establishing a connection when my phone was sleeping . ideally i would bring up the app, and it would reconnect with the most recent connection.

**Comment by doctor3w** [comment]
I think I can do this, on wake from sleep. But probably not from opening and closing the app, because then every time you open the app it will attempt a reconnect with the last device.

**Comment by andyburnett** [comment]
That sounds like a good plan. Once that is fixed I think we are close to having an actual release

**Comment by doctor3w** [comment]
Yeah I think so to. I am working on something pretty cool right now for the app. I somewhat redesigned it. I can change it back easily if needed, but it I redesigned the picker for duration to a custom one. In the next push tell me if you like it.

**Comment by andyburnett** [comment]
Sounds great. And I meant to say that I love the look of the app. It is a huge step forward. Very slick indeed.

**Comment by doctor3w** [comment]
Well I hope you like the new one I'm working on, I think it looks even better.

**Comment by doctor3w** [comment]
Alright, some sad news. To an iOS app, there seems to be no difference between closing an app and sleeping the phone while the app is open. Thus this makes it difficult to automatically reconnect with a device. I think I can get it to work though. Just going to take a little longer than I'd hoped.

**Comment by andyburnett** [comment]
I don't think there is a problem with reconnecting the last used device. Worse case it times out because it can't be found. But if it works - and it will most if the time, then we are good :-)

**Comment by doctor3w** [comment]
Sure thing, I'll get it working! How's the developer program account coming?

**Comment by andyburnett** [comment]
Auto reconnection seems to work really well!!
