### ISSUE TITLE
The Cancel button is too close to the Start button

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#21]
When you pause the timer, the cancel button appears directly under the start button. This is going to be trouble!

Could we move the cancel button to the footer, or at least further away?

**Comment by doctor3w** [comment]
I can, the only reason I put it there was because on a small screen like the iPhone 5, I'm pretty sure the cancel button will be directly underneath anyway. I could probably put it in the corner as well. I'll try and find what looks nicest.

**Comment by andyburnett** [comment]
Brill!

**Comment by doctor3w** [comment]
What do you think about this X in the corner as the cancel button?
![simulator screen shot jun 30 2016 9 41 15 am](https://cloud.githubusercontent.com/assets/1222887/16490255/dd24b206-3ea6-11e6-9282-71ea62af051a.png)

**Comment by andyburnett** [comment]
Could we put it in the middle of the footer? Just to keep it away from the other buttons.

**Comment by doctor3w** [comment]
Sure thing, do you like the X though? I don't want it to be confusing.

**Comment by andyburnett** [comment]
Are yes, I completely forgot to answer your question! Sorry about that.

I think the X is a perfectly good starting point. And, we'll find out what the users think.

**Comment by doctor3w** [comment]
Alright, sounds good.
