### ISSUE TITLE
Could we have a switch in the options to put the screen into fullscreen by default

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#22]
I am thinking that we will probably have a 'display' ipad. It would be good to have it always start in full screen, and we could probably do that with a slider in the options panel

**Comment by doctor3w** [comment]
Alright, that is something I could add to the settings. Something else I was wondering, because you probably don't change this often, what if we moved the Hard/Soft toggle to settings as well? I thought it would clean up the UI a little, but fine if we keep it where it is.

**Comment by andyburnett** [comment]
Actually, the hard/soft option is something we do need to change on the
fly. Basically, if someone is presenting, but they are e.g. nervous
speakers, or had problems with their slides, we might switch from hard to
soft, at that moment.

Cheers

**Comment by doctor3w** [comment]
Oh alright, makes sense! I'll keep it the way it is then!
