### ISSUE TITLE
UI: Layout of controller screen

### ISSUE THREAD

**Issue by dsl101** [Knowinnovation/bluetime#25]
It feels like the start button is lost in a sea of grey, and the spinners for choosing the time are too small. Could this be re-balanced a bit?

**Comment by doctor3w** [comment]
Too small? These are just the default Apple selection spinners used in most apps. I did recently make my own custom spinner to use, but I went back to this one because it was easier to work with in auto layout. But maybe we consider trying again on my custom one?

**Comment by doctor3w** [comment]
That UIPickerView is also set to a height of 162 which is Apple's height for it and it doesn't grow. If I make it taller it just expands to show more options and doesn't increase text size or anything.

**Comment by doctor3w** [comment]
![simulator screen shot jun 30 2016 10 50 31 am](https://cloud.githubusercontent.com/assets/1222887/16492655/86baff7e-3eb0-11e6-926c-61d26abc2b28.png)
This was the custom picker view I was working on because I didn't exactly like Apple's, but I was having trouble scaling in during rotation on the iPad. I put it off to the side but I could bring it back if we think the UIPickerView is too small or out of proportion to the rest.

**Comment by andyburnett** [comment]
Probably not worth the effort right now

**Comment by doctor3w** [comment]
Maybe a future version.

**Comment by dsl101** [comment]
It wasn't the text size that was the problem - it was the 'range' visible. Compare with the native timer app - you can see most of 3 above and below, and it gives more of an 'area' to touch/swipe to change.

**Comment by doctor3w** [comment]
Gotcha, I can make it larger, the reason for it being smaller was that on rotation on a small 4s phone, the picker would then cover the buttons.

**Comment by dsl101** [comment]
Surely we should be persecuting those still using the 4.

**Comment by doctor3w** [comment]
I'm working on something right now that should provide auto layout so the 4 is still usable while making it larger for those using larger phones.

**Comment by doctor3w** [comment]
Okay I just uploaded a new version which makes this about half the screen size on an iPhone 6s, so let me now if the size is still too small

**Comment by dsl101** [comment]
It still feels a bit cramped - like the spinners should take up two thirds of the screen, and the start / other controls one third, almost the reverse of current. In fact, should Start / Pause be the standard arrow / double vertical bars in the toolbar rather than buttons?

On the landscape view, perhaps these should be side by side? Anyway, not super urgent - it certainly works as is.

**Comment by doctor3w** [comment]
If you follow iPhone UI guidelines the UIPickerView Shouldn't be more than half the screen. The original intent of the design was to mimic the default Clock app timer but Andy changed a few things here and there so it's not as similar any more. But even in Apple's app, they don't have the picker taking up more than half and the buttons sort of just float in the grey.

**Comment by doctor3w** [comment]
After some research I found that the UIPickerView actually has a max height of 216 and will not go beyond that! So it's somewhat out of the question to increase the size of that top portion unless I use my custom picker.
