### ISSUE TITLE
Weirdness between phone and watch

### ISSUE THREAD

**Issue by dsl101** [Knowinnovation/bluetime#27]
I just selected a new time (1m1s) on the phone, started then paused the timer, then opened the watch app. The watch says 24 seconds! Not sure what's going on there...

**Comment by dsl101** [comment]
I think it was a previous timer on the watch which had reached +24s but that showed as 0:24 on the watch. Also, I'm now back at the watch showing the _old_ timer start value, not what's selected on the phone. So on my watch is says 0:01 (I had set a 1 second timer earlier), and on the phone is says 1m1s (changed manually on the phone). Clicking 'start' on the watch causes a new 1s timer to be shown on the phone, then it goes back to showing 1m1s on the spinners.

**Comment by dsl101** [comment]
In fact, I can't make the watch app update from it's original 1-second timer at all. I'm stuck with it, and when it expires, if I click Pause on the watch, it shows the number of seconds _since_ the timer expired (i.e. it's been counting up in the background and then shows this on the watch screen). If I _then_ click start, I get the timer counting up on the phone. Pause and Cancel then take it back to 00:01, even though on the phone the spinners say 1m1s

**Comment by doctor3w** [comment]
I just tried the watch myself and it just went haywire on me, I couldn't get it to do anything I want, so that's going to take reviewing.

**Comment by doctor3w** [comment]
So I just updated the watch app, I changed the timing structure on the phone and forgot to make that change on the watch as well. Now they should keep the same time.

**Comment by doctor3w** [comment]
Reopen this if it's not fixed.
