### ISSUE TITLE
Disable the start button unless connected

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#30]
I will describe this as an enhancement, but I think it might actually be closer to being a bug. In other words, we really do need this.

The issue is that when I start up the version on my iPhone, in an attempt to control the iPad display timer, I don't actually get any feedback about whether I am connected or not.

This is confusing.

I think it might be best if the buttons are greyed out – the start or pause button that is – until the connection is actually made. But there may be another way of doing it – changing the background colour of the screen – or something like that.

**Comment by doctor3w** [comment]
Alright, I can do something. Maybe like an icon showing that you are connected. I don't want to grey out the buttons because you should be able to use the timer without a connection.

**Comment by andyburnett** [comment]
Ok, an icon is good

**Comment by doctor3w** [comment]
Alright I'll work on an icon!
