### ISSUE TITLE
Watch app stopped working

### ISSUE THREAD

**Issue by dsl101** [Knowinnovation/bluetime#31]
Since switching to the TestFlight version, the watch app doesn't work for. The old icon disappeared and new one installed but I just got the swirling dots and now just a black watch screen with 'KiTimer' at the top

**Comment by doctor3w** [comment]
Really?? That's odd. Have you tried re-installing. You also might need to do something with trusting, I'm not sure but I'll look into that.

**Comment by dsl101** [comment]
Yes, trusted, removed, readded. Same result.

**Comment by doctor3w** [comment]
Interesting, if anything the UI should appear it should not just be blank.

**Comment by doctor3w** [comment]
I've been trying to fix this for a while now, I'm not actually sure what's wrong. I'm going to contact Apple, because the debugger doesn't show anything, the app literally just won't load.

**Comment by andyburnett** [comment]
That's annoying. 

I think we should triage this. If Apple, or their forums, can give you a pointer then great. Otherwise, disable the watch feature - for now - and let's get the first version approved by the App Store. 

I am sure there will be many more versions and improvements, but we do need to move on to the converge capability soon'ish

Cheers
Andy

**Comment by doctor3w** [comment]
I'm going to try one more thing and if it doesn't work, we'll move on without it. I have started building the base for converge already, just nothing usable to push yet

**Comment by andyburnett** [comment]
Brilliant!

**Comment by doctor3w** [comment]
Hallelujah it's fixed! I had to remake the entire project file, but it worked.

**Comment by andyburnett** [comment]
Ah, the programming equivalent of Ctrl + Alt + Del

**Comment by doctor3w** [comment]
What a process.

**Comment by doctor3w** [comment]
Could we change the repo name to KiTimer?

**Comment by andyburnett** [comment]
absolutely. please go right ahead  (or do I need to do that?)

**Comment by doctor3w** [comment]
I don't have editing control over this repo

**Comment by andyburnett** [comment]
Done

**Comment by doctor3w** [comment]
Perfect.

---

Drew Dunne
drew@drewsdunne.com
