### ISSUE TITLE
Loses time choice when force closed

### ISSUE THREAD

**Issue by dsl101** [Knowinnovation/bluetime#33]
If you force close the app, on relaunch it defaults back to 5 mins, not what you had previously selected. I would think it should survive that - and maybe even delete / reinstall.

**Comment by doctor3w** [comment]
Can't remember on delete/reinstall because it will delete any preferences I save too unless we add iCloud storage to the app. But I can do on kill and relaunch, I'll just store the last selected time in preferences.

**Comment by dsl101** [comment]
Delete reinstall probably should clear prefa, invade of corruption. But
kill and relaunch would be good. Tx

**Comment by doctor3w** [comment]
No problem, that's an easy add.
