### ISSUE TITLE
The check mark doesn't disappear when connection is lost

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#34]
Connect controller to a display device. Check mark is displayed. Exit from the app on the display device, check mark remains on controller device.

**Comment by doctor3w** [comment]
Alright I'll check this out before I release, technically they are still connected until you get the alert saying "Failed to Connect".

**Comment by doctor3w** [comment]
It should work now, I totally forgot to take it away on fail if Auto Accept is on. All better now
