### ISSUE TITLE
Pausing the phone doesn't pause the watch

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#35]
Start the count down via the phone. Watch also starts. Pause the phone, display unit pauses but the watch doesn't

**Comment by doctor3w** [comment]
Weird, I'm not having this issue between my watch and my phone while connected to another device.

**Comment by andyburnett** [comment]
I have just reinstalled the app on my watch. This might have fixed it

**Comment by doctor3w** [comment]
Perfect.
