### ISSUE TITLE
Apple Watch app

### ISSUE THREAD

**Issue by doctor3w** [Knowinnovation/bluetime#4]
pretty self explanatory

**Comment by doctor3w** [comment]
I got the Apple Watch app going but it's going to be a bit tricky to get the time working on the watch.

**Comment by andyburnett** [comment]
Oh that's a shame. What's the problem

**Comment by doctor3w** [comment]
So, the on the watch Apple actually offers a really nice view called a InterfaceTimer, which is extremely useful for making timers! I wish they offered that on the phone as well because it would make everything much easier. But because this is the recommended why to use timers on the watch, I have to figure out a way to convert my timing mechanism on the phone to theirs, which is just going to take a good sit down to think of a nice solution. Shouldn't be too difficult it would just be so much easier if Apple offered the same UI features on both the watch and the phone.
