### ISSUE TITLE
Watch button needs to update on hard stop

### ISSUE THREAD

**Issue by dsl101** [Knowinnovation/bluetime#40]
The watch button stills says 'pause' on timer end - it should probably switch to 'reset'?

**Comment by doctor3w** [comment]
Yes it is supposed to say cancel upon reaching zero. But I'm not having this error. When my timer reaches 0 on hard stop the buttons switch to cancel.

**Comment by doctor3w** [comment]
Are you sure you have the newest version of the Watch App? That means deleting it and re-installing from TestFlight. Because I can't seem to replicate this.

**Comment by andyburnett** [comment]
I had to reinstall the watch app.

**Comment by dsl101** [comment]
Sorry - it was on soft stop and I was confused when it stopped at zero
(other ticket).

**Comment by doctor3w** [comment]
Perfect. So I've fixed this as well. 

---

Drew Dunne
drew@drewsdunne.com
http://www.drewsdunne.com

On Tue, Jul 12, 2016 at 6:02 PM -0400, "dsl101" notifications@github.com wrote:

Sorry - it was on soft stop and I was confused when it stopped at zero

(other ticket).
