### ISSUE TITLE
Bluetooth connection doesn't seem to work

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/bluetime#42]
The target device appears, and allows you to connect to it, but the connection immediately drops.  Wifi connections are fine

**Comment by doctor3w** [comment]
Really? I can't seem to replicate this bug. I've turned WiFi off on my device and it connects fine.

**Comment by andyburnett** [comment]
I just got a successful connection, but I turned auto accept on first. I need to work through the various options to reproduce.

**Comment by andyburnett** [comment]
I can't reproduce the problem, so let's mark this as closed.
