### ISSUE TITLE
Sleeping the phone and backgrounding the app cause a disconnect

### ISSUE THREAD

**Issue by doctor3w** [Knowinnovation/bluetime#9]
This is probably a huge problem if you wanted to do other things while the phone was timing.

**Comment by andyburnett** [comment]
What if we were to run the process the other way around.  I.e. the ipad on
the presenter's desk is the official source of time, and the iphone is
simply a device that controls it, and also asks for the current time.

The on desk ipad won't go to sleep.

**Comment by doctor3w** [comment]
So right now, I have it so that each device has it's own "time". Like it's hosted on all devices. So the problem isn't much that the presenter's time would stop, it's more that once disconnected, in order to reconnect, the device needs to "accept" a connection from the controller. 

I already have it set up so that if the timer app is open, it prevents sleep.

**Comment by andyburnett** [comment]
Ah, I see what you mean. Hmm I wonder why my car reconnects with my phone. Is there a more permanent form of pairing that we could use?

**Comment by doctor3w** [comment]
Well, so the way the MultipeerConnectivity framework that Apple offers does not reallypair two devices. If we wanted to pair two devices like your car does one would use the CoreBluetooth framework, but I don't believe this is allowed between two iPhones. That's why they created the MultipeerConnectivity framework, for connections for things such as games or sharing between apps. Sadly this framework is limited in it's capabilities as the sessions seem to disconnect upon exiting the app because the devices are not paired but really just have a knowledge of another device.

**Comment by doctor3w** [comment]
Another possible solution to this is: 

We have the Presenter device (D1) and the controller device (D2). 
We could have it so the presenter device, when in fullscreen mode or maybe a presenter toggle, automatically accepts invitations and then outputs its data to any new connections. This would allow anyone who disconnected (D2) to reconnect by reopening their app, inviting D1 and then immediately being synced with D1's time and is now back in control. 

Right now I have something like this implemented but it's backwards at the moment and doesn't automatically accept. But that would be an easy fix. This may be the only solution at the moment unless I can find a way to actually pair two devices with CoreBluetooth. But that would most definitely restrict the amount of timers to 2 devices.

**Comment by andyburnett** [comment]
I like that idea. And maybe we add a shared Pin? Just to stop anyone from pairing at will?

**Comment by doctor3w** [comment]
Hmm we could add a pin, set in settings when you turn on automatic accept. But is it really that much of a security issue that people will try and connect willy-nilly? Definitely do-able though.

**Comment by andyburnett** [comment]
I think the risk is very low, and we can definitely make this a feature for a future release.

**Comment by doctor3w** [comment]
Alright, well it wouldn't be hard at all to write so maybe we could add that before we push it out to the app store. 

---

Drew Dunne
drew@drewsdunne.com
http://www.drewsdunne.com

On Wed, Jun 8, 2016 at 7:14 PM -0400, "andyburnett" notifications@github.com wrote:

I think the risk is very low, and we can definitely make this a feature for a future release.
